# Generated by Django 5.2.6 on 2025-09-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=2)),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='学籍号')),
                ('birthday', models.DateField(help_text='Formate : yyyy-mm-dd', verbose_name='出生日期')),
                ('contact_number', models.CharField(max_length=20, verbose_name='联系方式')),
                ('address', models.TextField(verbose_name='家庭住址')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_grade', to='grades.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
    ]
